Make search_string configurable for filtered_header_rule
trussworks/terraform-aws-wafv2 pull request #97
Opened 2022-07-27 14:25 UTC by neilharris123

Currently the `search_string` for `filtered_header_rules` must have the same value as the rule name. If the search string is a header value that is sensitive, the only way with the existing module to add it as the search string, is to use the name of the rule. I don't believe having the same value for rule name and and search string makes sense in most cases. 
This change preserves the previous behaviour, but allows user to set their own search_string.

2022-11-08 18:57 UTC, rpdelaney requested changes
Thank you for your contribution! I left a comment.

2022-11-08 18:57 UTC, rpdelaney commented on variables.tf
> +    search_string = string
It may be more idiomatic to default to `nil`, actually. I'm not sure.

2022-11-17 23:18 UTC, rpdelaney commented on variables.tf
> +    search_string = string
@esacteksab What do you think? If you agree I think we could fix this up and merge it.

2022-11-18 13:49 UTC, esacteksab commented on variables.tf
> +    search_string = string
Let's do it!

2022-11-18 16:05 UTC, rpdelaney commented on variables.tf
> +    search_string = string
How's this? 444b5d3 @esacteksab

2022-11-30 20:07 UTC, esacteksab commented on variables.tf
> +    search_string = string
LGTM

2022-11-30 20:16 UTC, rpdelaney approved these changes
per Barry

2022-11-30 20:18 UTC, merged

2022-11-30 20:29 UTC, rpdelaney commented
Shipped in `v2.6.0`